GET http://localhost:3000/users

###

GET http://localhost:3000/findUser
Content-Type: application/json

{
    "username": "Kyle"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Kyle",
    "password": "password"
}

###

DELETE  http://localhost:3000/delete
Content-Type: application/json

{
    "id": 7
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle",
    "password": "password"
}

###

Get http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJLeWxlIiwiaWF0IjoxNjQ0MzY5NzE3fQ.gDB8spysqRvuKC7InkdSPjZv8eMe7rF09Kcqi7Qqyb8

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVlbSIsImlhdCI6MTYzODU4NjU1MH0.ghzoXq_BeseispElrW0dOlFQCy7A7NNBg_7523dl4vc"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVlbSIsImlhdCI6MTYzODkzMTUzMH0.xxeHkT14z5dUjgUS-2GfZL0VCdfKP0IWeVImmidhGSI"
}

###

POST http://localhost:3000/log
Content-Type: application/json

{
    "username": ""
}

###

//This is for TOOLS

###

GET http://localhost:3000/findTool

###

POST http://localhost:3000/createTool
Content-Type: application/json

{
    "toolName": "Hammer",
    "available": "Yes",
    "ownerID": 4
}

###
DELETE  http://localhost:3000/deleteTool
Content-Type: application/json

{
    "toolName": "Hammer"
}

###

GET http://localhost:3000/getTools
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJLeWxlIiwiaWF0IjoxNjQ0MTkwNDQwfQ.ZUBGeuV46SqnniyEaTtc3BkFT_bUnLGPPp6yTUiG7eM

{
    "ownerID": 4
}