GET http://localhost:3000/users

###

GET http://localhost:3000/findUser
Content-Type: application/json

{
    "username": "Tom"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Betty",
    "password": "password"
}

###

DELETE  http://localhost:3000/delete
Content-Type: application/json

{
    "username": "Tom"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Tom",
    "password": "password"
}

###

Get http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbSIsImlkIjoiMSIsImlhdCI6MTY0ODY3MzMwM30.kMKjIuL34DvMhvubAh98MiHRjFGlGiKQJgfKqVenTwc

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVlbSIsImlhdCI6MTYzODU4NjU1MH0.ghzoXq_BeseispElrW0dOlFQCy7A7NNBg_7523dl4vc"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVlbSIsImlhdCI6MTYzODkzMTUzMH0.xxeHkT14z5dUjgUS-2GfZL0VCdfKP0IWeVImmidhGSI"
}

###

POST http://localhost:3000/log
Content-Type: application/json

{
    "username": ""
}

###

//This is for TOOLS

###

GET http://localhost:3000/findTool

###

POST http://localhost:3000/createTool
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbSIsImlkIjoiOCIsImlhdCI6MTY0NDQ1MTY4NH0.lLSFbLYsWMMjNJ-Yx8DhDu43U3N4StL8smnKss2l0Ls


{
    "toolName": "Pipe Wrench",
    "available": "Yes",
}

###
DELETE  http://localhost:3000/deleteTool/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbSIsImlkIjoiOCIsImlhdCI6MTY0NDQ1MTY4NH0.lLSFbLYsWMMjNJ-Yx8DhDu43U3N4StL8smnKss2l0Ls

###

GET http://localhost:3000/getTools
Content-Type: application/json

{
    "ownerID": 4
}

###

GET http://localhost:3000/oneTool
Content-Type: application/json

{
    "toolID": 8
}

###

GET http://localhost:3000/findMessage

###

POST http://localhost:3000/createMessage
Content-Type: application/json

{
    "message": "Available?",
    "senderID": 4,
    "recipientID": 10
}

###

DELETE  http://localhost:3000/deleteMessage/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNoYW5ub24iLCJpZCI6IjkiLCJpYXQiOjE2NDUwNTU4MTN9.fuQXPwNo0QKAgxnoeO1HpEuefT89WQw6XnlpaM5_FBM

###