GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Kyle",
    "password": "password"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "Kyle",
    "password": "password"
}

###

Get http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVlbSIsImlhdCI6MTYzODkzMTUzMCwiZXhwIjoxNjM4OTMyMTMwfQ.FscXN0bDdCjvmnTJj-7mJ348hAS9t4pySsMM2gBGocM

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVlbSIsImlhdCI6MTYzODU4NjU1MH0.ghzoXq_BeseispElrW0dOlFQCy7A7NNBg_7523dl4vc"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVlbSIsImlhdCI6MTYzODkzMTUzMH0.xxeHkT14z5dUjgUS-2GfZL0VCdfKP0IWeVImmidhGSI"
}

###

POST http://localhost:3000/log
Content-Type: application/json

{
    "username": "Beem"
}