name: Backend Test
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: DB_USER  
          POSTGRES_PASSWORD: DB_PASSWORD
          POSTGRES_DB: DB_NAME
          # POSTGRES_HOST: DB_HOST
          # POSTGRES_POST: 5432          
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          localhost:3000
        # - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: use node js
        uses: actions/setup-node@v3
        with: 
          node-version: '14.x'
      - run: npm ci
        working-directory: ./backend
      - run: npm run build --if-present
        working-directory: ./backend
      - run: npm run devStart
        working-directory: ./backend
      - run: npm test
        working-directory: ./backend